refactor(front/): Delete tailwindcss
MelvinCou/idee pull request #51
Opened 2024-04-07 16:01 UTC by MansourWolou

Vuetify come not only with vue component to speed up developpement process but with css library( like bootstrap ) too. Tailwind is not need since we are already using vuetify.

Default css class created by vuetify are not needed too

Linked #47

2024-04-08 09:49 UTC, MelvinCou requested changes
Add this plugin for eslint : https://www.npmjs.com/package/eslint-plugin-vuetify

2024-04-08 09:57 UTC, MelvinCou commented
> Add this plugin for eslint : https://www.npmjs.com/package/eslint-plugin-vuetify

This seems to look for deprecated features, nevermind.

2024-04-08 10:07 UTC, Nokomi6 commented on front/src/App.vue
> +              <v-btn variant="text" rounded> Edit Account </v-btn>
No space for text in html

2024-04-08 10:07 UTC, Nokomi6 commented on front/src/App.vue
> +<style scoped></style>
Remove if not used

2024-04-08 10:07 UTC, Nokomi6 commented on front/src/components/__tests__/HomeView.spec.ts
> +import { mount, shallowMount } from "@vue/test-utils";
Remove mount if not used

2024-04-08 13:50 UTC, MansourWolou commented
> Add this plugin for eslint : https://www.npmjs.com/package/eslint-plugin-vuetify

don't need

2024-04-09 07:00 UTC, MelvinCou approved these changes

2024-04-09 07:01 UTC, merged